### ISSUE TITLE
can you share the compiled version of this?

### ISSUE THREAD

**Issue by dovalie** [aderfa/star_rail#1]
im not a coder myself but im really interested in your cheat, so as many people are
can you share the .dll in this github, because the one on unknown is outdated

**Comment by caspaas** [comment]
its not outdated. but his source cant compile tho since it references to some stuff on his pc.

**Comment by aderfa** [comment]
new update not for public, i hear akebi already coded for this game maybe u can search

**Comment by aderfa** [comment]
![image](https://user-images.githubusercontent.com/77231874/236638214-97a2acd4-9c5a-4322-94ff-28ba821c6759.png)

**Comment by caspaas** [comment]
can i hit you up on discord?
Jace#0550

Willing to pay too

**Comment by dovalie** [comment]
> ![image](https://user-images.githubusercontent.com/77231874/236638214-97a2acd4-9c5a-4322-94ff-28ba821c6759.png)

im on akebi server i did not see any of this
guess we'll have to wait, sadly :/

**Comment by hntdahta** [comment]
> > ![image](https://user-images.githubusercontent.com/77231874/236638214-97a2acd4-9c5a-4322-94ff-28ba821c6759.png)
> 
> im on akebi server i did not see any of this guess we'll have to wait, sadly :/

already public on github tho
tested, only speedhack is useful lol

**Comment by zhongmof** [comment]
> > > ![图像](https://user-images.githubusercontent.com/77231874/236638214-97a2acd4-9c5a-4322-94ff-28ba821c6759.png)
> > 
> > 
> > 我在 Akebi 服务器上我没有看到任何这种猜测，我们将不得不等待，可悲的是：/
> 
> 已经在 GitHub 上公开测试，目前只有 speedhack 是有用的

Can you share its link

**Comment by aderfa** [comment]
I haven't tried it, maybe this

[i](https://github.com/Taiga74164/TurnBasedAnimeGame-Mod)

**Comment by caspaas** [comment]
i love how it says "for a certain turn based anime game"

**Comment by TuanAnh2901** [comment]
> I haven't tried it, maybe this
> 
> [Taiga Turn Base Anime Game](https://github.com/Taiga74164/TurnBasedAnimeGame-Mod)

I thought Taiga is still coding cheat for Akebi? but that repo is in the AkebiGC-Private so you can't see the newest code. He is coding ChestItem now

**Comment by hntdahta** [comment]
> > > > ![图像](https://user-images.githubusercontent.com/77231874/236638214-97a2acd4-9c5a-4322-94ff-28ba821c6759.png)
> > > 
> > > 
> > > 我在 Akebi 服务器上我没有看到任何这种猜测，我们将不得不等待，可悲的是：/
> > 
> > 
> > 已经在 GitHub 上公开测试，目前只有 speedhack 是有用的
> 
> Can you share its link

[](https://github.com/NctimeAza/StarRail-Cheat)

**Comment by caspaas** [comment]
just goto unicore.
cheap and has good options anyway
