### ISSUE TITLE
help me with this error

### ISSUE THREAD

**Issue by B3iMy** [aderfa/star_rail#10]
I did everything in your video but still getting this error when I build
![image](https://user-images.githubusercontent.com/109080505/236688463-bdbe52b9-e915-408a-9bc3-db0f3563dae3.png)

**Comment by aderfa** [comment]
Are u already add Minhook.lib ?

**Comment by B3iMy** [comment]
yes i did

**Comment by B3iMy** [comment]
now i got this 
![image](https://user-images.githubusercontent.com/109080505/236732606-403cdb5b-156a-446c-b116-78b3d41f8027.png)

**Comment by aderfa** [comment]
You already got it just use injector to inject dll, search injector to my other repository

**Comment by B3iMy** [comment]
oh my bad, I thought it was an exe file xD 
tks
