### ISSUE TITLE
I would like to request your help

### ISSUE THREAD

**Issue by zhongmof** [aderfa/star_rail#2]
Can you share your injector? My injector is not working

**Comment by zhongmof** [comment]
thank you

**Comment by aderfa** [comment]
try this
https://github.com/aderfa/injector

**Comment by zhongmof** [comment]
Thank you, I have successfully injected most of the functions of the DLL you posted on an unknown cheating forum that are not available

**Comment by zhongmof** [comment]
1>x64\Debug\hook.obj : warning LNK4042: 对象被多次指定；已忽略多余的指定
1>BypassEnable.obj : error LNK2019: 无法解析的外部符号 "void __cdecl hook::init(void)" (?init@hook@@YAXXZ)，函数 "void __cdecl enablebypass_new::init(void)" (?init@enablebypass_new@@YAXXZ) 中引用了该符号
1>C:\project\starrail\botline\Build\Debug(x64)\bin\bot.dll : fatal error LNK1120: 1 个无法解析的外部命令
1>已完成生成项目“ImGui DirectX 11 Kiero Hook.vcxproj”的操作 - 失败。

**Comment by zhongmof** [comment]
This is an error generated by vs when I ran the compilation myself

**Comment by aderfa** [comment]
did you already add minhook.lib to project??

**Comment by aderfa** [comment]
I've updated the code, try downloading and recompile
