### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lxyxpn** [aderfa/star_rail#3]
i can't build https://ibb.co/f0hzcLc

**Comment by aderfa** [comment]
go to general -> input then add Additional Dependencies -> add minhook.lib

**Comment by lxyxpn** [comment]
where is general i'm newbie coding ;-;

**Comment by aderfa** [comment]
press right button on your project, then select properties

![image](https://user-images.githubusercontent.com/77231874/236644928-2e3c1301-7353-46e7-9371-09a5be8c8b56.png)

go to linker then select input, now you can add minhook at Additional Dependencies
![image](https://user-images.githubusercontent.com/77231874/236644962-9036bd73-aaac-4e16-8e54-0fb755e44d96.png)

**Comment by aderfa** [comment]
I've updated the code, try downloading and recompile
