### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by tosterhvh** [aderfa/star_rail#4]
![image](https://user-images.githubusercontent.com/132790482/236649559-bd44c9c6-abe6-497d-aadc-03761c86fc14.png)

**Comment by aderfa** [comment]
I've updated the code, try downloading and recompile

**Comment by hujihan** [comment]
> 我已经更新了代码，尝试下载并重新编译

no still unsuccessful,Still this question

**Comment by tosterhvh** [comment]
> I've updated the code, try downloading and recompile

it didn't help

**Comment by aderfa** [comment]
> 

try rhis
https://www.youtube.com/watch?v=m_T1Wcow624&ab_channel=Botline
