### ISSUE TITLE
void init errors

### ISSUE THREAD

**Issue by cmmaio** [aderfa/star_rail#5]
![image](https://user-images.githubusercontent.com/121247685/236658399-2f10933a-e2f5-454c-aea9-d9d0a0d6b6eb.png)
cant fix this some reason have added the minhook library as well as compiled my own minhook and replaced the files

**Comment by hujihan** [comment]
`Rebuild started...
1>------ Rebuild All started: Project: Library, Configuration: Debug x64 ------
1>D:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2116,5): warning : The referenced project '..\..\..\..\..\EasyPeasy-GC-master\EasyPeasy-GC-master\EasyPeasy-GC launcher\EasyPeasy-GC launcher.vcxproj' does not exist.
1>autobattle.cpp
1>C:\Users\hujih\Downloads\star_rail-master\star_rail-master\ImGui DirectX 11 Kiero Hook\autobattle.h(17,2): warning C4091: 'typedef ': ignored on left of 'GamePhase' when no variable is declared
1>bypass.cpp
1>BypassEnable.cpp
1>e.cpp
1>C:\Users\hujih\Downloads\star_rail-master\star_rail-master\ImGui DirectX 11 Kiero Hook\autobattle.h(17,2): warning C4091: 'typedef ': ignored on left of 'GamePhase' when no variable is declared
1>FpsUnlock.cpp
1>C:\Users\hujih\Downloads\star_rail-master\star_rail-master\ImGui DirectX 11 Kiero Hook\autobattle.h(17,2): warning C4091: 'typedef ': ignored on left of 'GamePhase' when no variable is declared
1>globals.cpp
1>gm.cpp
1>C:\Users\hujih\Downloads\star_rail-master\star_rail-master\ImGui DirectX 11 Kiero Hook\autobattle.h(17,2): warning C4091: 'typedef ': ignored on left of 'GamePhase' when no variable is declared
1>C:\Users\hujih\Downloads\star_rail-master\star_rail-master\ImGui DirectX 11 Kiero Hook\gm.cpp(22,50): warning C4305: 'initializing': truncation from '__int64' to 'uint32_t'
1>C:\Users\hujih\Downloads\star_rail-master\star_rail-master\ImGui DirectX 11 Kiero Hook\gm.cpp(22,37): warning C4309: 'initializing': truncation of constant value
1>hook.cpp
1>C:\Users\hujih\Downloads\star_rail-master\star_rail-master\ImGui DirectX 11 Kiero Hook\autobattle.h(17,2): warning C4091: 'typedef ': ignored on left of 'GamePhase' when no variable is declared
1>imgui.cpp
1>imgui_demo.cpp
1>imgui_draw.cpp
1>imgui_impl_dx11.cpp
1>imgui_impl_win32.cpp
1>imgui_widgets.cpp
1>kiero.cpp
1>kntl.cpp
1>Logger.cpp
1>main.cpp
1>C:\Users\hujih\Downloads\star_rail-master\star_rail-master\ImGui DirectX 11 Kiero Hook\autobattle.h(17,2): warning C4091: 'typedef ': ignored on left of 'GamePhase' when no variable is declared
1>mesum.cpp
1>C:\Users\hujih\Downloads\star_rail-master\star_rail-master\ImGui DirectX 11 Kiero Hook\autobattle.h(17,2): warning C4091: 'typedef ': ignored on left of 'GamePhase' when no variable is declared
1>ohk.cpp
1>C:\Users\hujih\Downloads\star_rail-master\star_rail-master\ImGui DirectX 11 Kiero Hook\autobattle.h(17,2): warning C4091: 'typedef ': ignored on left of 'GamePhase' when no variable is declared
1>Generating Code...
1>Compiling...
1>player.cpp
1>C:\Users\hujih\Downloads\star_rail-master\star_rail-master\ImGui DirectX 11 Kiero Hook\autobattle.h(17,2): warning C4091: 'typedef ': ignored on left of 'GamePhase' when no variable is declared
1>sh.cpp
1>C:\Users\hujih\Downloads\star_rail-master\star_rail-master\ImGui DirectX 11 Kiero Hook\autobattle.h(17,2): warning C4091: 'typedef ': ignored on left of 'GamePhase' when no variable is declared
1>short.cpp
1>C:\Users\hujih\Downloads\star_rail-master\star_rail-master\ImGui DirectX 11 Kiero Hook\autobattle.h(17,2): warning C4091: 'typedef ': ignored on left of 'GamePhase' when no variable is declared
1>ult.cpp
1>C:\Users\hujih\Downloads\star_rail-master\star_rail-master\ImGui DirectX 11 Kiero Hook\autobattle.h(17,2): warning C4091: 'typedef ': ignored on left of 'GamePhase' when no variable is declared
1>utils.cpp
1>Generating Code...
1>buffer.c
1>hde32.c
1>hde64.c
1>hook.c
1>trampoline.c
1>Generating Code...
1>x64\Debug\hook.obj : warning LNK4042: object specified more than once; extras ignored
1>BypassEnable.obj : error LNK2019: unresolved external symbol "void __cdecl hook::init(void)" (?init@hook@@YAXXZ) referenced in function "void __cdecl enablebypass_new::init(void)" (?init@enablebypass_new@@YAXXZ)
1>C:\Users\hujih\Downloads\star_rail-master\star_rail-master\Build\Debug(x64)\bin\bot.dll : fatal error LNK1120: 1 unresolved externals
1>Done building project "ImGui DirectX 11 Kiero Hook.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
========== Rebuild started at 1:10 PM and took 12.752 seconds ==========`
![QQ图片20230507131055](https://user-images.githubusercontent.com/46958243/236658982-ac5093c2-9be2-4ab3-9973-a33a62fb7863.png)
![QQ截图20230507131114](https://user-images.githubusercontent.com/46958243/236658987-20f7a679-6ca6-4191-a93f-6f54a7387d60.png)

**Comment by aderfa** [comment]
try this

https://www.youtube.com/watch?v=m_T1Wcow624&ab_channel=Botline
