### ISSUE TITLE
include.obj 

### ISSUE THREAD

**Issue by onionbbaw** [aderfa/star_rail#6]
![image](https://user-images.githubusercontent.com/132803739/236659602-2cc2216a-a09d-4dd4-a93f-5ffd5f15b8a8.png)
help pls

**Comment by tosterhvh** [comment]
add minhook.lib in address

**Comment by onionbbaw** [comment]
> 

like this?
![image](https://user-images.githubusercontent.com/132803739/236670154-0edeeb45-4dfd-4be6-abf2-9672c05b3c86.png)
error again 
![image](https://user-images.githubusercontent.com/132803739/236670267-ce71cfdb-05f5-4323-b9ab-f56be1c25933.png)

**Comment by onionbbaw** [comment]
> add minhook.lib in address

or this 
![image](https://user-images.githubusercontent.com/132803739/236670367-b58bbc5f-eb05-4ab5-8c73-1e020e435273.png)
become this 
![image](https://user-images.githubusercontent.com/132803739/236670397-08aa278b-2f0d-4c86-8434-8613ec19e652.png)

**Comment by tosterhvh** [comment]
> > add minhook.lib in address
> 
> or this ![image](https://user-images.githubusercontent.com/132803739/236670367-b58bbc5f-eb05-4ab5-8c73-1e020e435273.png) become this ![image](https://user-images.githubusercontent.com/132803739/236670397-08aa278b-2f0d-4c86-8434-8613ec19e652.png)

this

**Comment by aderfa** [comment]
https://www.youtube.com/watch?v=m_T1Wcow624&ab_channel=Botline

**Comment by onionbbaw** [comment]
> https://www.youtube.com/watch?v=m_T1Wcow624&ab_channel=Botline

thank it work but with only debug build 
maybe my problem is build as release

**Comment by onionbbaw** [comment]
> https://www.youtube.com/watch?v=m_T1Wcow624&ab_channel=Botline

is noclip work? or hotkey

**Comment by aderfa** [comment]
saya menghapus noclip untuk beberapa alasan

**Comment by aderfa** [comment]
i remove noclip for some reason
