### ISSUE TITLE
LNK1107 invalid or corrupt file : cannot read at 0x 1E05

### ISSUE THREAD

**Issue by keexers** [aderfa/star_rail#7]
hey, i'm having troubles with your code. because i'm not sure whether it's the minhook.h file is having problems or it's just an issue on my end

can you possibly help me fix this error? do i have to redownload minhook.h from the official one?

![image](https://user-images.githubusercontent.com/89464478/236663950-632f2498-85c4-4005-90be-de60ea928e7c.png)

**Comment by aderfa** [comment]
try use kiero minhook.h
