### ISSUE TITLE
LNK2001	无法解析的外部符号 "void __cdecl hook::init(void)" (?init@hook@@YAXXZ)

### ISSUE THREAD

**Issue by awaxiaoyu** [aderfa/star_rail#8]
![image](https://user-images.githubusercontent.com/125581307/236676214-85d35d70-84b2-425d-9d69-94e24c7ef896.png)
There are always correction errors, and the solution you provided cannot solve it

**Comment by aderfa** [comment]
U already watch my yt? I upload how to solve there

**Comment by awaxiaoyu** [comment]
> 你已经看我的yt了吗？我上传如何在那里解决

I followed suit, but every time I made some modifications and recompiled, I would continue to report errors, and then I had to do it again according to the video

**Comment by aswirl4** [comment]
> U already watch my yt? I upload how to solve there

I removed the easyPeasy reference as you said in README. But the errors are still there.
Btw your youtube gets no video if this is your yt [Nor Abdillah](https://www.youtube.com/@Botline)

**Comment by aderfa** [comment]
https://www.youtube.com/watch?v=m_T1Wcow624&ab_channel=Botline
